/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "your_thrift_file_constants.h"

namespace Test {

const your_thrift_fileConstants g_your_thrift_file_constants;

your_thrift_fileConstants::your_thrift_fileConstants() {
}

} // namespace

