/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ProxyServer_H
#define ProxyServer_H

#include <thrift/TDispatchProcessor.h>
#include "server_types.h"



class ProxyServerIf {
 public:
  virtual ~ProxyServerIf() {}
  virtual void fetchURL(std::string& _return, const std::string& url) = 0;
};

class ProxyServerIfFactory {
 public:
  typedef ProxyServerIf Handler;

  virtual ~ProxyServerIfFactory() {}

  virtual ProxyServerIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ProxyServerIf* /* handler */) = 0;
};

class ProxyServerIfSingletonFactory : virtual public ProxyServerIfFactory {
 public:
  ProxyServerIfSingletonFactory(const boost::shared_ptr<ProxyServerIf>& iface) : iface_(iface) {}
  virtual ~ProxyServerIfSingletonFactory() {}

  virtual ProxyServerIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ProxyServerIf* /* handler */) {}

 protected:
  boost::shared_ptr<ProxyServerIf> iface_;
};

class ProxyServerNull : virtual public ProxyServerIf {
 public:
  virtual ~ProxyServerNull() {}
  void fetchURL(std::string& /* _return */, const std::string& /* url */) {
    return;
  }
};

typedef struct _ProxyServer_fetchURL_args__isset {
  _ProxyServer_fetchURL_args__isset() : url(false) {}
  bool url;
} _ProxyServer_fetchURL_args__isset;

class ProxyServer_fetchURL_args {
 public:

  ProxyServer_fetchURL_args() : url() {
  }

  virtual ~ProxyServer_fetchURL_args() throw() {}

  std::string url;

  _ProxyServer_fetchURL_args__isset __isset;

  void __set_url(const std::string& val) {
    url = val;
  }

  bool operator == (const ProxyServer_fetchURL_args & rhs) const
  {
    if (!(url == rhs.url))
      return false;
    return true;
  }
  bool operator != (const ProxyServer_fetchURL_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProxyServer_fetchURL_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProxyServer_fetchURL_pargs {
 public:


  virtual ~ProxyServer_fetchURL_pargs() throw() {}

  const std::string* url;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProxyServer_fetchURL_result__isset {
  _ProxyServer_fetchURL_result__isset() : success(false) {}
  bool success;
} _ProxyServer_fetchURL_result__isset;

class ProxyServer_fetchURL_result {
 public:

  ProxyServer_fetchURL_result() : success() {
  }

  virtual ~ProxyServer_fetchURL_result() throw() {}

  std::string success;

  _ProxyServer_fetchURL_result__isset __isset;

  void __set_success(const std::string& val) {
    success = val;
  }

  bool operator == (const ProxyServer_fetchURL_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProxyServer_fetchURL_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProxyServer_fetchURL_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProxyServer_fetchURL_presult__isset {
  _ProxyServer_fetchURL_presult__isset() : success(false) {}
  bool success;
} _ProxyServer_fetchURL_presult__isset;

class ProxyServer_fetchURL_presult {
 public:


  virtual ~ProxyServer_fetchURL_presult() throw() {}

  std::string* success;

  _ProxyServer_fetchURL_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ProxyServerClient : virtual public ProxyServerIf {
 public:
  ProxyServerClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  ProxyServerClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void fetchURL(std::string& _return, const std::string& url);
  void send_fetchURL(const std::string& url);
  void recv_fetchURL(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ProxyServerProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<ProxyServerIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ProxyServerProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_fetchURL(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ProxyServerProcessor(boost::shared_ptr<ProxyServerIf> iface) :
    iface_(iface) {
    processMap_["fetchURL"] = &ProxyServerProcessor::process_fetchURL;
  }

  virtual ~ProxyServerProcessor() {}
};

class ProxyServerProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ProxyServerProcessorFactory(const ::boost::shared_ptr< ProxyServerIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< ProxyServerIfFactory > handlerFactory_;
};

class ProxyServerMultiface : virtual public ProxyServerIf {
 public:
  ProxyServerMultiface(std::vector<boost::shared_ptr<ProxyServerIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ProxyServerMultiface() {}
 protected:
  std::vector<boost::shared_ptr<ProxyServerIf> > ifaces_;
  ProxyServerMultiface() {}
  void add(boost::shared_ptr<ProxyServerIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void fetchURL(std::string& _return, const std::string& url) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->fetchURL(_return, url);
    }
    ifaces_[i]->fetchURL(_return, url);
    return;
  }

};



#endif
